### ISSUE TITLE
Upload Foto Profil baru

### ISSUE THREAD

**Issue by yukebrillianth** [upkoding/upkoding#21]
Saat hapus foto lama dan upload foto baru, gambar yang di load tetap foto yang lama

**Comment by ekaputra07** [comment]
@yukebrillianth apakah setelah memilih foto yang aka diupload, tombol "Simpan" nya sudah di klick? karena saat ini proses upload tidak otomatis, jadi ketika melakukan perubahan tertentu, harus klik tombol simpan.

**Comment by ekaputra07** [comment]
Closed. Karena tidak ada respon dan tidak ada pengguna lain yg melaporkan masalah serupa. Kalau masih mengalami masalah yang sama silahkan buka issue ini lagi.
