### ISSUE TITLE
App: Forum diskusi

### ISSUE THREAD

**Issue by ekaputra07** [upkoding/upkoding#4]
Disini user bisa bertanya dan menjawab pertanyaan dari user lainnya.

Topic yang didiskusikan bisa umum, bisa juga berhubungan dengan proyek.

**Comment by rociretama** [comment]
saya mau buat proyek yg penghitung berat badan ideal itu, tolong minta cluenya teman2

**Comment by ekaputra07** [comment]
Maaf ya @rociretama sampe kesini nanyanya 🙂  mudah2an forumnya disegerakan.

Jadi itu bebas mau pake apa aja, untuk mengetes kemampuan diri aja, bisa berupa web, app atau desktop.
yg penting harus sesuai sepesifikasi/requirements disini:
https://www.upkoding.com/proyek/aplikasi-penghitung-berat-badan-ideal-2/

Contoh, ini salah satu teman kita dia cuma pake CodePen (pake HTML/JS aja):
https://www.upkoding.com/proyek/aplikasi-penghitung-berat-badan-ideal-2/oskaresvada/

Bukan tentang apa yg dipakai tapi lebih ke ketika dikasi task dengan requirements tertentu, bisa mengerjakan ndak, gitu aja.

**Comment by rociretama** [comment]
Ok bg, ini lagi buat dari java netbean bg

Rab, 17 Mar 2021 pukul 02.10 Eka Putra ***@***.***> menulis:

**Comment by ekaputra07** [comment]
@rociretama siip santai aja ini platform belajar bukan perlombaan, kalau bisa aplikasinya sampai jadi ya. Klo yang disubmit itu baru codenya, kita ingin lihat demonya 🙂

**Comment by rociretama** [comment]
Iya benar jg bg, kebawa semangat ngoding bg hehe

Kam, 18 Mar 2021 pukul 05.43 Eka Putra ***@***.***> menulis:
