### ISSUE TITLE
Connection not secure: in the browser

### ISSUE THREAD

**Issue by study-hary-id** [upkoding/upkoding#7]
Jika kita mengakses website UpKoding dengan mengetikkan `upkoding.com` secara langsung, maka situsnya di anggap tidak aman oleh browser.

| Browser | Image |
| -------- | -------|
| Safari | ![Safari](https://user-images.githubusercontent.com/75228229/111030635-f5637080-8435-11eb-9369-c02dcc877b0a.png) |
| Firefox | ![Firefox](https://user-images.githubusercontent.com/75228229/111030337-365a8580-8434-11eb-8377-d2ad8e1ba42e.png) |
| Edge/Chrome | ![Edge/Chrome](https://user-images.githubusercontent.com/75228229/111030591-b46b5c00-8435-11eb-9411-869c44836784.png) |

Tapi jika mengaksesnya menggunakan **https** ✅`https://upkoding.com` maka browser akan tetap menganggapnya aman.

**Comment by ekaputra07** [comment]
Terima kasih @study-hary-id sudah diperbaiki 🙏👍
Disini: https://github.com/upkoding/upkoding/blob/main/upkoding/settings.py#L163

**Comment by ekaputra07** [comment]
@study-hary-id btw itu gimana caranya bikin screenshot cantik gitu ya? 😁

**Comment by study-hary-id** [comment]
> @study-hary-id btw itu gimana caranya bikin screenshot cantik gitu ya? 😁

Saya cuma pake aplikasi screenshot yg ada dari utilities mac mas,
terus pilih yg capture selected window,
terus arahin pointernya ke window aplikasi yg mau di screenshot mas.

Terus saya kelompokan menggunakan table supaya enak bacanya
